<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>Data Access logic components of Application use case of HR application</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPUA.Application.DataAccessLogic\BPUA.Application.DataAccessLogic.csproj" />
    <ProjectReference Include="..\HR.Application.Contracts\HR.Application.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <DomainName>HR</DomainName>
    <UseCaseName>Application</UseCaseName>
    <PluginFolderSubdir>HR</PluginFolderSubdir>
  </PropertyGroup>
</Project>
