<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>BPUA Host Application</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <None Update="bpua.host.appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="bpua.host.appsettings.schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
