<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>State machine components for applications based on BPUA</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPUA.Application.CommonComponents\BPUA.Application.CommonComponents.csproj" />
    <ProjectReference Include="..\BPUA.Application.Context\BPUA.Application.Context.csproj" />
    <ProjectReference Include="..\BPUA.Application.Contracts\BPUA.Application.Contracts.csproj" />
    <ProjectReference Include="..\BPUA.Core\BPUA.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="StateComponents\" />
  </ItemGroup>
</Project>
