<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="9.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPUA.Application.Extensions.Services\BPUA.Application.Extensions.Services.csproj" />
    <ProjectReference Include="..\BPUA.Application.Orchestration\BPUA.Application.Orchestration.csproj" />
  </ItemGroup>

</Project>
