<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>BPUA application HTTP components contracts</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
