<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>Core components for applications based on BPUA</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
