<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>Hosting components for applications based on BPUA</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="JsonSchema.Net" Version="9.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPUA.Application.BusinessLogic\BPUA.Application.BusinessLogic.csproj" />
    <ProjectReference Include="..\BPUA.Application.DataAccessLogic\BPUA.Application.DataAccessLogic.csproj" />
    <ProjectReference Include="..\BPUA.Application.DataProcessingLogic\BPUA.Application.DataProcessingLogic.csproj" />
    <ProjectReference Include="..\BPUA.Application.Extensions.Services\BPUA.Application.Extensions.Services.csproj" />
    <ProjectReference Include="..\BPUA.Application.Orchestration\BPUA.Application.Orchestration.csproj" />
  </ItemGroup>
</Project>
