<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\\SharedBuildSettings.props" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute">
      <_Parameter1>Business logic components of BPUA Application use case</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPUA.Application.ProcessComponents\BPUA.Application.ProcessComponents.csproj" />
    <ProjectReference Include="..\PocoDataSet.BpuaExtensions\PocoDataSet.BpuaExtensions.csproj" />
  </ItemGroup>

</Project>
